// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHevIyliqqXGIyERn5b82p_lfJnKpj9fg',
    appId: '1:437533535038:web:3d885a9a547ed6a2369a6f',
    messagingSenderId: '437533535038',
    projectId: 'flutter-auth-demo-2026',
    authDomain: 'flutter-auth-demo-2026.firebaseapp.com',
    storageBucket: 'flutter-auth-demo-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUIAWeaVQgSoxvJlv3BSdbPRKo8MdO_LQ',
    appId: '1:437533535038:android:e26aa1f4b8d7ea4d369a6f',
    messagingSenderId: '437533535038',
    projectId: 'flutter-auth-demo-2026',
    storageBucket: 'flutter-auth-demo-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUsdpAOhGfvQMidp2ThAbLxf5t-p-eIbA',
    appId: '1:437533535038:ios:ddaafe262d60ddbe369a6f',
    messagingSenderId: '437533535038',
    projectId: 'flutter-auth-demo-2026',
    storageBucket: 'flutter-auth-demo-2026.firebasestorage.app',
    iosBundleId: 'com.example.newTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUsdpAOhGfvQMidp2ThAbLxf5t-p-eIbA',
    appId: '1:437533535038:ios:ddaafe262d60ddbe369a6f',
    messagingSenderId: '437533535038',
    projectId: 'flutter-auth-demo-2026',
    storageBucket: 'flutter-auth-demo-2026.firebasestorage.app',
    iosBundleId: 'com.example.newTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHevIyliqqXGIyERn5b82p_lfJnKpj9fg',
    appId: '1:437533535038:web:b70edd53c2d042a2369a6f',
    messagingSenderId: '437533535038',
    projectId: 'flutter-auth-demo-2026',
    authDomain: 'flutter-auth-demo-2026.firebaseapp.com',
    storageBucket: 'flutter-auth-demo-2026.firebasestorage.app',
  );
}
